### ISSUE TITLE
Issue when building on Ubuntu 20.04

### ISSUE THREAD

**Issue by MaticConradi** [EKA2L1/EKA2L1#161]
Getting this error when running `make` and I'm not sure what it's about. I did some googling, and it seems as if some other projects have a similar issue.

Building on Linux Ubuntu 20.04.

```bash
[  3%] Building C object src/external/filediag/CMakeFiles/nativefilediag.dir/src/nfd_gtk.c.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/gtk-3.0/gdk/gdktypes.h:35,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/parallels/Documents/EKA2L1/src/external/filediag/src/nfd_gtk.c:10:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
make[2]: *** [src/external/filediag/CMakeFiles/nativefilediag.dir/build.make:76: src/external/filediag/CMakeFiles/nativefilediag.dir/src/nfd_gtk.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1242: src/external/filediag/CMakeFiles/nativefilediag.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by pent0** [comment]
We already disabled tests of the cubeb dependency [here](https://github.com/EKA2L1/EKA2L1/blob/ecb9a4160218f1466ae75d67719b0dcbd192c1c4/src/external/CMakeLists.txt#L149), this is because you may accidently manually enable it again if you use CMake UI.

Please delete cache, reconfigure, dont tick untick any option, build again. To save time, you can also build only the console target, whichh will  produce the executable. Thanks a lot. If you want live support, you can go to Discord to contact me, thanks.

**Comment by pent0** [comment]
Hi, have you resolved the problems yet? Thanks!

**Comment by MaticConradi** [comment]
Yup, it successfully got built now, thanks
