### ISSUE TITLE
Multiplayer Bluetooth Support.

### ISSUE THREAD

**Issue by ahmed3110c** [EKA2L1/EKA2L1#262]
Is it possible to implement Bluetooth in the app to support multiplayer feature? It would be great addition for this project for playing coop in titles like Explode Arena.

**Comment by testman42** [comment]
There are two ways this could be interpreted:
* Online multiplayer, where Bluetooth traffic is wrapped into [internet protocol suite](https://en.wikipedia.org/wiki/Internet_protocol_suite) (like TCP, UDP), basically simulating Bluetooth connection over the internet.
* Actual Bluetooth multiplayer, where two clients would use hardware's Bluetooth capability to connect.

I wonder what kind of funky hacks would have to be implemented in order to get software written for [N-Gage's Bluetooth 1.1](https://www.gsmarena.com/nokia_n_gage_qd-748.php) to communicate over modern internet or current versions of Bluetooth protocol.

**Comment by pent0** [comment]
I added basic netplay, follow thhe  description in Discord channel testing for more info.  Sorry that I can not write a more in depth tutorial for now. Its just scrambled messages.

**Comment by testman42** [comment]
Can this be closed now? As netplay is a thing now.
