### ISSUE TITLE
Games doesn't work in EKA2L1 but N-Gage games did

### ISSUE THREAD

**Issue by Lucas-mother3** [EKA2L1/EKA2L1#266]
So, hi dev, I just run some games on EKA2L1 (Nokia 5320 games) but it did black screen then crashes then restarts. But some N-Gage games (SonicN, Crash Nitro Kart, Asphalt: Urban GT 2 (with graphical glitches here and there), Virtua Cop, Rayman 3). N-gage Call of Duty just hangs, KOF Extreme just stuck at white screen (after the character select screen), Tony Hawk Pro Skater just hangs at loading screen.

The Nokia 5320 and 5530 games crashes every time, even simply Opera Mini 7.1 just crashes.
Please fix it dev.

Device: Huawei Y6 Prime 2019 (MRD-LX1F)
Processor: MediaTek Helio A22 (MT6761)
CPU: Quad-core 2.0 GHz Cortex-A53
GPU: PowerVR GE8320
RAM: 2GB
Internal Storage: 32GB

**Comment by pent0** [comment]
1. There are some specifics setup needed for N-Gage games, some does not work. We take the issues through compability repo
2. simply Opera Mini 7.1 is not simply, application tends to do more then games, you can see game consoles where they leave applications to emulate last. A large number of games work, some does not work. 5530 is not supported on 32-bit Android

Please visit the Discord server for assist on game problems. This issue is very wide-ranged
