### ISSUE TITLE
Unable to launch games on ngage 2.0 suddenly

### ISSUE THREAD

**Issue by srgtsilent** [EKA2L1/EKA2L1#317]
For some reason I am now unable to launch any games I install through the data/n-gage/e folder [method ](https://www.reddit.com/r/metalgearsolid/comments/o3lavl/metal_gear_solid_mobile_has_been_finally_emulated/) Even after rebooting and reinstalling. 
 this is the most common error on my currect version - W D:\a\EKA2L1\EKA2L1\src\emu\services\src\ui\cap\oom_app.cpp:136 [Service.UI]: Unimplemented opcode for OOM AKNCAP server: 0x54, fake return with epoc::error_none

[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6905785/EKA2L1.log)

**Comment by pent0** [comment]
Please show me the screenshot of you have installed the game and if possible, a video demonstrating the problem. Have you installed the game before and then update?

**Comment by srgtsilent** [comment]
of course. For reference this happens on every game, this happened when EKA was in documents, desktop, or a sub directory of desktop. Happened when I ran it as admin or normal. This happened on both the old version i was running that had a black sandbox like GUI, and this current one I am using with a white GUI. 

[Troubleshooting Video](https://youtu.be/PQS1DEeD-s0)

If there is anything else you need let me know.
[EKA2L1.log](https://github.com/EKA2L1/EKA2L1/files/6907693/EKA2L1.log)

**Comment by pent0** [comment]
Since this is experimental works, and you have tried it from long time ago and again. Something might be incompatible with new versions, which if it's (configurations or so), I won't have plan to comply. I really suggest you to reinstall the device first (backup old files!), if it's still like that, I will try to look again.

Please access data/drives/c/20020b79/ and backup the whole folder, it contains all your save files.

**Comment by pent0** [comment]
To make it clear, nothing in the GUI indicates any possible error. The one that you tell me has a WARNING in it, and is regular occurence.

**Comment by srgtsilent** [comment]
alright. So its more likely a spontaneous problem with my system then with the emulator. Thanks. I will see if I did anything on my end. Atleast it seems it must be on my end. And ill try some other versions to see aswell.

**Comment by pent0** [comment]
Nope, I mean the emulator changed so frequently, that experimental feature like n-gage 2.0 can not guarantee to be stable across other version of the emulator, especially since you don't keep track much, it may be broken because of compabilities change. 

I only suggest you to backup the data folder and starts another new one, reinstalling the 5320 and the game! After that if it is still not crash, that may be a problem with your computer, and I will try to support as much as I can. Sorry if any confusion is caused.

**Comment by pent0** [comment]
Hi, does it work now for you? If not, you can contact me on the Discord server to receive live support on this topic. Sorry.

**Comment by pent0** [comment]
I will assume the like is the Yes. Any problems forward please visit the Discord for live support, or open another issue if you don't feel comfortable on Discord.
