### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by pent0** [EKA2L1/EKA2L1#58]
Deprecated Tracking FBS List

**Comment by pent0** [comment]
Actually, GetNearestFont will get the font with the same name first. If it doesn't exist, it will check other fonts. I can store a pointer cache of all matching fonts till date. 

The matching algorithm is not easy, I can't understand difference between max height and design height. If I know what it means, i will get on implementing right away.

**Comment by pent0** [comment]
Max height and design height is confusing.

Here is how it works: If the exact font can't be found (its name and algorithic style doesn't match), it will filters out those with the similar spec. The one which is closed the most to the thing called *max height* get pick.

**Comment by pent0** [comment]
MBM loader and opcode implementation jobs are taken by @pent0

**Comment by pent0** [comment]
MBM loading are done, we now needs some magic to draw to screen.

**Comment by pent0** [comment]
FBS opcodes are missing and needs to be filled more:
See original [header](https://github.com/SymbianSource/oss.FCL.sf.os.graphics/blob/ff133bc50e6158bfb08cc093b0f0055321dcde99/fbs/fontandbitmapserver/inc/FbsMessage.H#L22) and [EKA2L1 header](https://github.com/EKA2L1/EKA2L1/blob/master/src/emu/epoc/include/epoc/services/fbs/fbs.h)
-

**Comment by TRR95** [comment]
Reopened to help easily remember what been worked on, that said, it goes into "Near Future" because most of the stuff won't be needed until EKA2L1 team tries to add some vary advanced features (for example, making Device Roms bootable)

furthermore, those reading this, don't expect any vary advanced features anytime soon. this is just list for the Dev's
